### ISSUE TITLE
DSM 7 says invalid format. any help? 

### ISSUE THREAD

**Issue by alokc83** [ukdtom/WTInstaller#31]
Thank you so much for writing this cool installer.

**Comment by trumpy81** [comment]
The installer is no longer being developed and development stopped long before DSM 7 was released.

Since Plex no longer support plugins, I suggest you look into WebTools-NG, a stand alone program that replaces the plugin and runs on your PC/Laptop.

For more details, see the [WebTools-NG Wiki](https://github.com/WebTools-NG/WebTools-NG/wiki)
